//
//  Data.swift
//  Cookpedia
//
//  Created by Bilal Dallali on 11/03/2023.
//

import Foundation

struct Country {
    let name: String
    let flag: String
    let domain: String
}

let countryList = [
    Country(name: "Afghanistan", flag: "afghanistan", domain: "AF"),
    Country(name: "Afrique du Sud", flag: "south-africa", domain: "ZA"),
    Country(name: "Albanie", flag: "albania", domain: "AL"),
    Country(name: "Algérie", flag: "algeria", domain: "DZ"),
    Country(name: "Allemagne", flag: "germany", domain: "DE"),
    Country(name: "Andorre", flag: "andorra", domain: "AD"),
    Country(name: "Angola", flag: "angola", domain: "AO"),
    Country(name: "Antigua-et-Barbuda", flag: "antigua-and-barbuda", domain: "AG"),
    Country(name: "Arabie saoudite", flag: "saudi-arabia", domain: "SA"),
    Country(name: "Argentine", flag: "argentina", domain: "AR"),
    Country(name: "Arménie", flag: "armenia", domain: "AM"),
    Country(name: "Australie", flag: "australia", domain: "AU"),
    Country(name: "Autriche", flag: "austria", domain: "AT"),
    Country(name: "Azerbaïdjan", flag: "azerbaidjan", domain: "AZ"),
    Country(name: "Bahamas", flag: "bahamas", domain: "BS"),
    Country(name: "Bahreïn", flag: "bahrain", domain: "BH"),
    Country(name: "Bangladesh", flag: "bangladesh", domain: "BD"),
    Country(name: "Barbade", flag: "barbados", domain: "BB"),
    Country(name: "Belgique", flag: "belgium", domain: "BE"),
    Country(name: "Belize", flag: "belize", domain: "BZ"),
    Country(name: "Bénin", flag: "benin", domain: "BJ"),
    Country(name: "Bhoutan", flag: "bhutan", domain: "BT"),
    Country(name: "Biélorussie", flag: "belarus", domain: "BY"),
    Country(name: "Birmanie", flag: "burma", domain: "MM"),
    Country(name: "Bolivie", flag: "bolivia", domain: "BO"),
    Country(name: "Bosnie-Herzégovine", flag: "bosnia-and-herzegovina", domain: "BA"),
    Country(name: "Botswana", flag: "botswana", domain: "BW"),
    Country(name: "Brésil", flag: "brazil", domain: "BR"),
    Country(name: "Brunei", flag: "brunei", domain: "BN"),
    Country(name: "Bulgarie", flag: "bulgaria", domain: "BG"),
    Country(name: "Burkina Faso", flag: "burkina-faso", domain: "BF"),
    Country(name: "Burundi", flag: "burundi", domain: "BI"),
    Country(name: "Cambodge", flag: "cambodia", domain: "KH"),
    Country(name: "Cameroun", flag: "cameroon", domain: "CM"),
    Country(name: "Canada", flag: "canada", domain: "CA"),
    Country(name: "Cap-Vert", flag: "cap-vert", domain: "CV"),
    Country(name: "Centrafrique", flag: "center-africa", domain: "CF"),
    Country(name: "Chili", flag: "chile", domain: "CL"),
    Country(name: "Chine", flag: "china", domain: "CN"),
    Country(name: "Chypre", flag: "cyprus", domain: "CY"),
    Country(name: "Colombie", flag: "colombia", domain: "CO"),
    Country(name: "Comores", flag: "comoros", domain: "KM"),
    Country(name: "Congo-Brazzaville", flag: "congo-brazzaville", domain: "CG"),
    Country(name: "Congo-Kinshasa", flag: "congo-kinshasa", domain: "CD"),
    Country(name: "Corée du Nord", flag: "north-korea", domain: "KP"),
    Country(name: "Corée du Sud", flag: "south-korea", domain: "KR"),
    Country(name: "Costa Rica", flag: "costa-rica", domain: "CR"),
    Country(name: "Côte d'Ivoire", flag: "cote-d'ivoire", domain: "CI"),
    Country(name: "Croatie", flag: "croatia", domain: "HR"),
    Country(name: "Cuba", flag: "cuba", domain: "CU"),
    Country(name: "Danemark", flag: "denmark", domain: "DK"),
    Country(name: "Djibouti", flag: "djibouti", domain: "DJ"),
    Country(name: "Dominique", flag: "dominique", domain: "DM"),
    Country(name: "Égypte", flag: "egypt", domain: "EG"),
    Country(name: "Émirats arabes unis", flag: "uae", domain: "AE"),
    Country(name: "Équateur", flag: "ecuador", domain: "EC"),
    Country(name: "Érythrée", flag: "eritrea", domain: "ER"),
    Country(name: "Espagne", flag: "spain", domain: "ES"),
    Country(name: "Estonie", flag: "estonia", domain: "EE"),
    Country(name: "États-Unis", flag: "usa", domain: "US"),
    Country(name: "Éthiopie", flag: "ethiopia", domain: "ET"),
    Country(name: "Fidji", flag: "fiji", domain: "FJ"),
    Country(name: "Finlande", flag: "finland", domain: "FI"),
    Country(name: "France", flag: "france", domain: "FR"),
    Country(name: "Gabon", flag: "gabon", domain: "GA"),
    Country(name: "Gambie", flag: "gambia", domain: "GM"),
    Country(name: "Géorgie", flag: "georgia", domain: "GE"),
    Country(name: "Ghana", flag: "ghana", domain: "GI"),
    Country(name: "Grèce", flag: "greece", domain: "GR"),
    Country(name: "Grenade", flag: "grenada", domain: "GD"),
    Country(name: "Guatemala", flag: "guatemala", domain: "GT"),
    Country(name: "Guinée-Bissau", flag: "guinea-bissau", domain: "GW"),
    Country(name: "Guinée-Conakry", flag: "guinea-conakry", domain: "GN"),
    Country(name: "Guinée équatoriale", flag: "equatorial-guinea", domain: "GQ"),
    Country(name: "Guyana", flag: "guyana", domain: "GY"),
    Country(name: "Haïti", flag: "haiti", domain: "HT"),
    Country(name: "Honduras", flag: "honduras", domain: "HN"),
    Country(name: "Hongrie", flag: "hungary", domain: "HU"),
    Country(name: "Inde", flag: "india", domain: "IN"),
    Country(name: "Indonésie", flag: "indonesia", domain: "ID"),
    Country(name: "Irak", flag: "irak", domain: "IQ"),
    Country(name: "Iran", flag: "iran", domain: "IR"),
    Country(name: "Irlande", flag: "ireland", domain: "IE"),
    Country(name: "Islande", flag: "iceland", domain: "IS"),
    Country(name: "Italie", flag: "italia", domain: "IT"),
    Country(name: "Jamaïque", flag: "jamaica", domain: "JM"),
    Country(name: "Japon", flag: "japan", domain: "JP"),
    Country(name: "Jordanie", flag: "jordan", domain: "JO"),
    Country(name: "Kazakhstan", flag: "kazakhstan", domain: "KZ"),
    Country(name: "Kenya", flag: "kenya", domain: "KE"),
    Country(name: "Kirghizistan", flag: "kyrgyzstan", domain: "KG"),
    Country(name: "Kiribati", flag: "kirbati", domain: "KI"),
    Country(name: "Kosovo", flag: "kosovo", domain: "YU"),
    Country(name: "Koweït", flag: "kuwait", domain: "KW"),
    Country(name: "Laos", flag: "laos", domain: "LA"),
    Country(name: "Lesotho", flag: "lesotho", domain: "LS"),
    Country(name: "Lettonie", flag: "latvia", domain: "LV"),
    Country(name: "Liban", flag: "lebanon", domain: "LB"),
    Country(name: "Liberia", flag: "liberia", domain: "LR"),
    Country(name: "Libye", flag: "libya", domain: "LY"),
    Country(name: "Liechtenstein", flag: "liechtenstein", domain: "LI"),
    Country(name: "Lituanie", flag: "lithuania", domain: "LT"),
    Country(name: "Luxembourg", flag: "luxembourg", domain: "LU"),
    Country(name: "Macédoine", flag: "macedonia", domain: "MK"),
    Country(name: "Madagascar", flag: "madagascar", domain: "MG"),
    Country(name: "Malaisie", flag: "malaysia", domain: "MY"),
    Country(name: "Malawi", flag: "malawi", domain: "MW"),
    Country(name: "Maldives", flag: "maldives", domain: "MV"),
    Country(name: "Mali", flag: "mali", domain: "ML"),
    Country(name: "Malte", flag: "malta", domain: "MT"),
    Country(name: "Maroc", flag: "morocco", domain: "MA"),
    Country(name: "Îles Marshall", flag: "marshall", domain: "MH"),
    Country(name: "Île Maurice", flag: "mauritius", domain: "MU"),
    Country(name: "Mauritanie", flag: "mauritania", domain: "MR"),
    Country(name: "Mexique", flag: "mexico", domain: "MX"),
    Country(name: "Micronésie", flag: "micronesia", domain: "FM"),
    Country(name: "Moldavie", flag: "moldova", domain: "MD"),
    Country(name: "Monaco", flag: "monaco", domain: "MC"),
    Country(name: "Mongolie", flag: "mongolia", domain: "MN"),
    Country(name: "Monténégro", flag: "montenegro", domain: "ME"),
    Country(name: "Mozambique", flag: "mozambique", domain: "MZ"),
    Country(name: "Namibie", flag: "namibie", domain: "NA"),
    Country(name: "Nauru", flag: "nauru", domain: "NR"),
    Country(name: "Népal", flag: "nepal", domain: "NP"),
    Country(name: "Nicaragua", flag: "nicaragua", domain: "NI"),
    Country(name: "Niger", flag: "niger", domain: "NE"),
    Country(name: "Nigeria", flag: "nigeria", domain: "NG"),
    Country(name: "Norvège", flag: "norway", domain: "NO"),
    Country(name: "Nouvelle-Zélande", flag: "new-zealand", domain: "NZ"),
    Country(name: "Oman", flag: "oman", domain: "OM"),
    Country(name: "Ouganda", flag: "uganda", domain: "UG"),
    Country(name: "Ouzbékistan", flag: "uzbekistan", domain: "UZ"),
    Country(name: "Pakistan", flag: "pakistan", domain: "PK"),
    Country(name: "Palaos", flag: "palau", domain: "PW"),
    Country(name: "Palestine", flag: "palestine", domain: "PS"),
    Country(name: "Panama", flag: "panama", domain: "PA"),
    Country(name: "Papouasie-Nouvelle-Guinée", flag: "papua-new-guinea", domain: "PG"),
    Country(name: "Paraguay", flag: "paraguay", domain: "PY"),
    Country(name: "Pays-Bas", flag: "netherlands", domain: "NL"),
    Country(name: "Pérou", flag: "peru", domain: "PE"),
    Country(name: "Philippines", flag: "philippines", domain: "PH"),
    Country(name: "Pologne", flag: "poland", domain: "PL"),
    Country(name: "Porto Rico", flag: "porto-rico", domain: "PR"),
    Country(name: "Portugal", flag: "portugal", domain: "PT"),
    Country(name: "Qatar", flag: "qatar", domain: "QA"),
    Country(name: "République dominicaine", flag: "dominican-republic", domain: "DO"),
    Country(name: "République Tchèque", flag: "czech-republic", domain: "CZ"),
    Country(name: "Roumanie", flag: "romania", domain: "RO"),
    Country(name: "Royaume-Unis", flag: "uk", domain: "UK"),
    Country(name: "Russie", flag: "russia", domain: "RU"),
    Country(name: "Rwanda", flag: "rwanda", domain: "RW"),
    Country(name: "Saint-Christophe-et-Nièves", flag: "saint-kitts-and-nevis", domain: "KN"),
    Country(name: "Sainte-Lucie", flag: "saint-lucia", domain: "LC"),
    Country(name: "Saint-Martin", flag: "san-marino", domain: "SM"),
    Country(name: "Saint-Vincent-et-les-Grenadines", flag: "saint-vincent-and-the-grenadines", domain: "VC"),
    Country(name: "Îles Salomon", flag: "solomon-islands", domain: "SB"),
    Country(name: "São-Tomé-et-Príncipe", flag: "sao-tome-and-principe", domain: "ST"),
    Country(name: "Salvador", flag: "salvador", domain: "SV"),
    Country(name: "Samoa occidentales", flag: "samoa", domain: "WS"),
    Country(name: "Sénégal", flag: "senegal", domain: "SN"),
    Country(name: "Serbie", flag: "serbia", domain: "RS"),
    Country(name: "Seychelles", flag: "seychelles", domain: "SC"),
    Country(name: "Sierra Leone", flag: "sierra-leone", domain: "SL"),
    Country(name: "Singapour", flag: "singapore", domain: "SG"),
    Country(name: "Slovaquie", flag: "slovakia", domain: "SK"),
    Country(name: "Slovénie", flag: "slovenia", domain: "SI"),
    Country(name: "Somalie", flag: "somalia", domain: "SO"),
    Country(name: "Soudan", flag: "sudan", domain: "SD"),
    Country(name: "Soudan du Sud", flag: "south-sudan", domain: "SS"),
    Country(name: "Sri Lanka", flag: "sri-lanka", domain: "LK"),
    Country(name: "Suède", flag: "sweden", domain: "SE"),
    Country(name: "Suisse", flag: "switzerland", domain: "CH"),
    Country(name: "Surinam", flag: "suriname", domain: "SR"),
    Country(name: "Swaziland", flag: "swaziland", domain: "SZ"),
    Country(name: "Syrie", flag: "syria", domain: "SY"),
    Country(name: "Tadjikistan", flag: "tajikistan", domain: "TJ"),
    Country(name: "Taïwan", flag: "taiwan", domain: "TW"),
    Country(name: "Tanzanie", flag: "tanzania", domain: "TZ"),
    Country(name: "Tchad", flag: "chad", domain: "TD"),
    Country(name: "Timor oriental", flag: "timor-leste", domain: "TL"),
    Country(name: "Thaïlande", flag: "thailand", domain: "TH"),
    Country(name: "Togo", flag: "togo", domain: "TG"),
    Country(name: "Tonga", flag: "tonga", domain: "TO"),
    Country(name: "Trinité-et-Tobago", flag: "trinidad-and-tobago", domain: "TT"),
    Country(name: "Tunisie", flag: "tunisia", domain: "TN"),
    Country(name: "Turkménistan", flag: "turkmenistan", domain: "TM"),
    Country(name: "Turquie", flag: "turkey", domain: "TR"),
    Country(name: "Tuvalu", flag: "tuvalu", domain: "TV"),
    Country(name: "Ukraine", flag: "ukraine", domain: "UA"),
    Country(name: "Uruguay", flag: "uruguay", domain: "UY"),
    Country(name: "Vanuatu", flag: "vanuatu", domain: "VU"),
    Country(name: "Vatican", flag: "vatican", domain: "CA"),
    Country(name: "Venezuela", flag: "venezuela", domain: "VE"),
    Country(name: "Vietnam", flag: "vietnam", domain: "VN"),
    Country(name: "Yémen", flag: "yemen", domain: "YE"),
    Country(name: "Zambie", flag: "zambia", domain: "ZM"),
    Country(name: "Zimbabwe", flag: "zimbabwe", domain: "ZW"),
]

